/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const SimulationRecord = IDL.Record({
  'peakPredatorCount' : IDL.Nat,
  'daysElapsed' : IDL.Nat,
  'seed' : IDL.Nat,
  'peakPlantCount' : IDL.Nat,
  'peakMammalCount' : IDL.Nat,
  'timestamp' : Time,
  'peakBirdCount' : IDL.Nat,
  'peakInsectCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLast10Records' : IDL.Func([], [IDL.Vec(SimulationRecord)], ['query']),
  'saveSimulationRecord' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const SimulationRecord = IDL.Record({
    'peakPredatorCount' : IDL.Nat,
    'daysElapsed' : IDL.Nat,
    'seed' : IDL.Nat,
    'peakPlantCount' : IDL.Nat,
    'peakMammalCount' : IDL.Nat,
    'timestamp' : Time,
    'peakBirdCount' : IDL.Nat,
    'peakInsectCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLast10Records' : IDL.Func([], [IDL.Vec(SimulationRecord)], ['query']),
    'saveSimulationRecord' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };